Book Store : Add styling
forLoop94/book-store pull request #4
Opened 2023-06-15 21:10 UTC by forLoop94

1. I added all missing JSX elements to the project (without adding extra functionality)
2. The final design matches Zeplin's design

2023-06-15 21:48 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @forLoop94 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ App runs smoothly
✔️ No linter errors
✔️ No inline styling

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)

## Required Changes ♻️
_Check the comments under the review 👇🏽 _

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-15 21:48 UTC, Ghiftee commented on src/styles/BookList.module.css
> +.blue {
- [ ] Kindly ensure that the following highlighted elements in the image have the same color as in the [zeplin design](https://app.zeplin.io/project/5b35a9e13227086040f8eb75/screen/5b695e29bb8c844f118f9378) as per the requirements

<img width="1430" alt="Screenshot 2023-06-15 at 22 33 49" src="https://github.com/forLoop94/book-store/assets/64774936/6ca8979e-0b4a-4a7b-b5c9-3006ce26c9db">

2023-06-15 21:48 UTC, Ghiftee commented on src/styles/app.module.css
> +  padding: 1.3rem;
- [ ] Kindly ensure that your app has the same spacing between elements as the given design and that the missing designs highlighted below are added.

<img width="1231" alt="Screenshot 2023-06-15 at 22 20 24" src="https://github.com/forLoop94/book-store/assets/64774936/2d53821f-da52-4ee7-841e-f9e35af9dc5d">

2023-06-15 21:48 UTC, Ghiftee commented on src/styles/BookList.module.css
> +}
- [ ] Kindly ensure that the elements spacing, the color and the size of the input fields and button in your form matches the given design.
- [ ] Also, please add the horizontal line highlighted in red as it is a part of the design

### Your design
<img width="1369" alt="Screenshot 2023-06-15 at 22 20 05" src="https://github.com/forLoop94/book-store/assets/64774936/f0aaafc1-96d1-4ab8-984a-8d6233e75df1">

### Given design

<img width="1075" alt="Screenshot 2023-06-15 at 22 41 37" src="https://github.com/forLoop94/book-store/assets/64774936/8ea17fb0-aafb-4ae6-a96f-0c5634fdc82a">

2023-06-16 14:03 UTC, divinecharlotte approved these changes
# Hello @forLoop94      😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive pr👍 
- Design 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 12:05 UTC, merged